version: '3'

services:
  nginx-le:
    container_name: 'nginx-letsencrypt'
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/nginx-le/nginx.conf:/etc/nginx/conf.d/default.conf
      - /docker/nginx-le/.htpasswd/:/etc/nginx/.htpasswd/
      - /docker/nginx-le/dh-param/:/etc/nginx/dh-param/
      - /docker/nginx-le/site-www:/usr/share/nginx/html:ro
      - /docker/nginx-le/letsencrypt/etc/letsencrypt/live/monsite.mondomaine.com/fullchain.pem:/etc/letsencrypt/live/monsite.mondomaine.com/fullchain.pem
      - /docker/nginx-le/letsencrypt/etc/letsencrypt/live/monsite.mondomaine.com/privkey.pem:/etc/letsencrypt/live/monsite.mondomaine.com/privkey.pem
      - /root/ssl/monsite.mondomaine.com/certs/fullchain.ecc.pem:/etc/letsencrypt/live/monsite.mondomaine.com/fullchain-ecc.pem
      - /root/ssl/monsite.mondomaine.com/private/privkey.ecc.pem:/etc/letsencrypt/live/monsite.mondomaine.com/privkey-ecc.pem
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
